/*
Vatstack API Specification

A suite of VAT APIs which let you validate VAT numbers with government services, look up VAT rates by ISO country code, calculate price quotes with centralized VAT rules and store transactions with each sale for VAT reporting.

API version: 1.3.0
Contact: team@vatstack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vatstack

import (
	"encoding/json"
)

// checks if the GetAllQuotes200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllQuotes200Response{}

// GetAllQuotes200Response struct for GetAllQuotes200Response
type GetAllQuotes200Response struct {
	// True if this list has another page of items after this one that can be fetched.
	HasMore bool `json:"has_more"`
	QuotesCount int32 `json:"quotes_count"`
	Quotes []Quote `json:"quotes"`
}

// NewGetAllQuotes200Response instantiates a new GetAllQuotes200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllQuotes200Response(hasMore bool, quotesCount int32, quotes []Quote) *GetAllQuotes200Response {
	this := GetAllQuotes200Response{}
	this.HasMore = hasMore
	this.QuotesCount = quotesCount
	this.Quotes = quotes
	return &this
}

// NewGetAllQuotes200ResponseWithDefaults instantiates a new GetAllQuotes200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllQuotes200ResponseWithDefaults() *GetAllQuotes200Response {
	this := GetAllQuotes200Response{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *GetAllQuotes200Response) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *GetAllQuotes200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *GetAllQuotes200Response) SetHasMore(v bool) {
	o.HasMore = v
}

// GetQuotesCount returns the QuotesCount field value
func (o *GetAllQuotes200Response) GetQuotesCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.QuotesCount
}

// GetQuotesCountOk returns a tuple with the QuotesCount field value
// and a boolean to check if the value has been set.
func (o *GetAllQuotes200Response) GetQuotesCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuotesCount, true
}

// SetQuotesCount sets field value
func (o *GetAllQuotes200Response) SetQuotesCount(v int32) {
	o.QuotesCount = v
}

// GetQuotes returns the Quotes field value
func (o *GetAllQuotes200Response) GetQuotes() []Quote {
	if o == nil {
		var ret []Quote
		return ret
	}

	return o.Quotes
}

// GetQuotesOk returns a tuple with the Quotes field value
// and a boolean to check if the value has been set.
func (o *GetAllQuotes200Response) GetQuotesOk() ([]Quote, bool) {
	if o == nil {
		return nil, false
	}
	return o.Quotes, true
}

// SetQuotes sets field value
func (o *GetAllQuotes200Response) SetQuotes(v []Quote) {
	o.Quotes = v
}

func (o GetAllQuotes200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllQuotes200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["quotes_count"] = o.QuotesCount
	toSerialize["quotes"] = o.Quotes
	return toSerialize, nil
}

type NullableGetAllQuotes200Response struct {
	value *GetAllQuotes200Response
	isSet bool
}

func (v NullableGetAllQuotes200Response) Get() *GetAllQuotes200Response {
	return v.value
}

func (v *NullableGetAllQuotes200Response) Set(val *GetAllQuotes200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllQuotes200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllQuotes200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllQuotes200Response(val *GetAllQuotes200Response) *NullableGetAllQuotes200Response {
	return &NullableGetAllQuotes200Response{value: val, isSet: true}
}

func (v NullableGetAllQuotes200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllQuotes200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


